services:
  db:
    image: postgres:16
    container_name: workout_tracker_db
    environment:
      POSTGRES_USER: kai
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: workout_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kai"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
